/** @typedef {'basic'|'pro'|'expert'|'elite'} SubscriptionTierKey */

export const TIER_FEATURES = {
  basic: {
    portfolioPhotos: 5,
    portfolioVideos: 0,
    activeSkillTypes: 1,
    locationScope: 'city',
    monthlyReplies: 5,
    canPostMarketplace: false,
    marketplaceListings: 0,
    canApplyJobBoard: false,
    hasBooking: false,
    hasInvoicing: false,
    hasQuotes: false,
    hasContracts: false,
    hasCRM: false,
    crmLimit: 0,
    hasClientPortal: false,
    hasBrandKit: false,
    hasPortfolioWebsite: false,
    hasInsights: false,
    hasDeliver: false,
    deliverStorageGb: 0,
    hasTeam: false,
    hasReviewRequests: false,
    hasReviews: false,
    importedReviews: 0,
    hasResponseTimeBadge: false,
    hasSearchCardImage: false,
    homepageRotation: false,
    eliteSpotlight: false,
    searchPriority: 4,
    sponsorCodesVisible: false,
  },
  pro: {
    portfolioPhotos: 20,
    portfolioVideos: 1,
    activeSkillTypes: 2,
    locationScope: 'state',
    monthlyReplies: 20,
    canPostMarketplace: true,
    marketplaceListings: 5,
    canApplyJobBoard: true,
    hasBooking: true,
    hasInvoicing: true,
    hasQuotes: false,
    hasContracts: false,
    hasCRM: false,
    crmLimit: 0,
    hasClientPortal: false,
    hasBrandKit: false,
    hasPortfolioWebsite: false,
    hasInsights: false,
    hasDeliver: false,
    deliverStorageGb: 0,
    hasTeam: false,
    hasReviewRequests: true,
    hasReviews: true,
    importedReviews: 5,
    hasResponseTimeBadge: true,
    hasSearchCardImage: true,
    homepageRotation: false,
    eliteSpotlight: false,
    searchPriority: 3,
    sponsorCodesVisible: true,
  },
  expert: {
    portfolioPhotos: 40,
    portfolioVideos: 5,
    activeSkillTypes: 4,
    locationScope: 'national',
    monthlyReplies: 999999,
    canPostMarketplace: true,
    marketplaceListings: 15,
    canApplyJobBoard: true,
    hasBooking: true,
    hasInvoicing: true,
    hasQuotes: true,
    hasContracts: true,
    hasCRM: true,
    crmLimit: 500,
    hasClientPortal: true,
    hasBrandKit: true,
    hasPortfolioWebsite: true,
    portfolioWebsiteType: 'single',
    hasInsights: true,
    hasDeliver: true,
    deliverStorageGb: 50,
    hasTeam: false,
    hasReviewRequests: true,
    hasReviews: true,
    importedReviews: 5,
    hasResponseTimeBadge: true,
    hasSearchCardImage: true,
    homepageRotation: true,
    eliteSpotlight: false,
    searchPriority: 2,
    sponsorCodesVisible: true,
  },
  elite: {
    portfolioPhotos: 999999,
    portfolioVideos: 999999,
    activeSkillTypes: 8,
    locationScope: 'national',
    monthlyReplies: 999999,
    canPostMarketplace: true,
    marketplaceListings: 999999,
    canApplyJobBoard: true,
    hasBooking: true,
    hasInvoicing: true,
    hasQuotes: true,
    hasContracts: true,
    hasCRM: true,
    crmLimit: 999999,
    hasClientPortal: true,
    hasBrandKit: true,
    hasPortfolioWebsite: true,
    portfolioWebsiteType: 'multi',
    hasCustomDomain: true,
    hasInsights: true,
    hasTeamInsights: true,
    hasDeliver: true,
    deliverStorageGb: 200,
    hasTeam: true,
    teamMemberLimit: 5,
    hasStudioProfile: true,
    hasReviewRequests: true,
    hasReviews: true,
    importedReviews: 5,
    hasResponseTimeBadge: true,
    hasSearchCardImage: true,
    homepageRotation: true,
    eliteSpotlight: true,
    searchPriority: 1,
    sponsorCodesVisible: true,
  },
}

/**
 * Normalizes DB / UI tier strings so gating matches Stripe and profiles.
 * @param {unknown} raw
 * @returns {SubscriptionTierKey}
 */
export function normalizeSubscriptionTier(raw) {
  let t = String(raw ?? 'basic').toLowerCase().trim()
  if (t === 'vip') return 'elite'
  if (['basic', 'pro', 'expert', 'elite'].includes(t)) return t
  return 'basic'
}

/**
 * @param {unknown} tier
 * @returns {typeof TIER_FEATURES.basic}
 */
export function getFeatures(tier) {
  const key = normalizeSubscriptionTier(tier)
  return TIER_FEATURES[key] || TIER_FEATURES.basic
}
